[project]
name = "klicstudio-mcp-server"
version = "0.1.0"
description = "mcp for the klicstudio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
]
